### ISSUE TITLE
Hide reCAPTCHA badge

### ISSUE THREAD

**Issue by mshindal** [mshindal/tabchat#2]
The reCAPTCHA badge is annoying and gets in the way of seeing comments. It should be hidden, following the guidelines [here](https://developers.google.com/recaptcha/docs/faq#id-like-to-hide-the-recaptcha-badge.-what-is-allowed).

**Comment by moonsuyoung** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
Hannnn, @sravan-s, @atc0m, @non-descriptive, @eonun, @ez-krk, @bakabird, @danoctavian, @scalaview, @alexmedison, @peekabo0, @LyuDun, @alvinc21, @kassol, @yfdyh000, @breakind, @r-a-v-a-s, @daysprilv, @miyuki811, @zhenruyan, @tiroq, @OrangeTux, @amatecha, @jaQbiak, @Nigirimeshi, @handlerww, @guanguanchuangyu, @jeffawang, @odinggg, @odziezmeska, @marcialwushu, @ZerosunGitHub, @QGB, @iamzdave, @yonixw, @devhe4d, @jieruypoe, @betgar, @Aierus, @yurenfenghua, @netsharec, @paven627, @Dangeranger, @lee2sman, @geekbuf, @barbuslex, @edwardshao, @24bulut, @NeilyoSummer, @tiefpunkt

**Comment by QGB** [comment]
join-pane
